### ISSUE TITLE
missing pair_uint64_bytes.first (type=uint64)

### ISSUE THREAD

**Issue by NatPDeveloper** [AntelopeIO/cdt#90]
I'm getting another failing unit test with the latest CDT version for vRAM.

```
  15 passing (2m)
  1 failing

  1) IPFS Service Test Contract
       IPFS Load Manifest:
     Error: missing pair_uint64_bytes.first (type=uint64)
      at Object.serializeStruct [as serialize] (node_modules/eosjs/dist/eosjs-serialize.js:571:27)
      at Object.serializeArray [as serialize] (node_modules/eosjs/dist/eosjs-serialize.js:640:26)
      at Object.serializeStruct [as serialize] (node_modules/eosjs/dist/eosjs-serialize.js:564:28)
      at Object.serializeStruct [as serialize] (node_modules/eosjs/dist/eosjs-serialize.js:564:28)
      at serializeActionData (node_modules/eosjs/dist/eosjs-serialize.js:1041:12)
      at Object.serializeAction (node_modules/eosjs/dist/eosjs-serialize.js:1051:15)
      at Api.<anonymous> (node_modules/eosjs/dist/eosjs-api.js:278:71)
      at step (node_modules/eosjs/dist/eosjs-api.js:47:23)
      at Object.next (node_modules/eosjs/dist/eosjs-api.js:28:53)
      at fulfilled (node_modules/eosjs/dist/eosjs-api.js:19:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Steps to reproduce:

Install zeus and unbox ipfs-dapp-service box.

```
npm i -g @liquidapps/zeus-cmd
mkdir ipfs-dapp-service
cd ipfs-dapp-service
zeus box create
zeus unbox ipfs-dapp-service
# update CMake files in ./contracts/eos as needed to support new cdt
zeus compile # or cmake . && make in ./contracts/eos
zeus test ipfsconsumer --services ipfs --chain eos --single-chain
```

See https://github.com/AntelopeIO/cdt/issues/15 for additional install instructions.

Last version this worked on was 3.0.0. Did not work on 3.0.1 with same error.

**Comment by mikelik** [comment]
I have built and installed newest CDT from main.
Currently I have following error when I try to build the contracts:
```
$ make
[  1%] Performing build step for 'dappservices'
[ 50%] Building CXX object CMakeFiles/dappservices.dir/dappservices.cpp.obj
In file included from /home/mikel/tmp/ipfs-dapp-service/contracts/eos/dappservices/dappservices.cpp:1:
In file included from /home/mikel/tmp/ipfs-dapp-service/contracts/eos/dappservices/./dappservices.hpp:8:
In file included from /usr/opt/cdt/3.2.0-dev/bin/../include/eosiolib/contracts/eosio/eosio.hpp:8:
/usr/opt/cdt/3.2.0-dev/bin/../include/eosiolib/contracts/eosio/multi_index.hpp:780:33: error: use of undeclared identifier 'get_type'
         using type = decltype( get_type(std::make_index_sequence<Num>{}) );
                                ^
```
although get_type is declared in line 772 (line above).
Maybe newer standard has to be used?

**Comment by mikelik** [comment]
I have created separate issue #137 for above issue.
After building CDT from commit 950e7415 I managed to reproduce the issue.
However I don't know what is step `Load Manifest:` which fails.

Anyway I see that the old abi file is different than new abi file and though the problem:
![image](https://user-images.githubusercontent.com/2914819/232033738-84df47ff-0a60-4802-b53d-df7b2e6e8a92.png)

Full diff:
```
147c147
<                     "name": "first",
---
>                     "name": "key",
151c151
<                     "name": "second",
---
>                     "name": "value",
917a918
>     "kv_tables": {},
921c922
< }
\ No newline at end of file
---
> }
```

**Comment by mikelik** [comment]
I have found the same issue with more description: https://github.com/AntelopeIO/cdt/issues/51
The reason of behavior described here is because of issue #34
Basing on Areg's comment: https://github.com/AntelopeIO/cdt/issues/34#issuecomment-1249751535 I would suggest to close this issue, because 3.0.1 is backward incompatible with 3.0.0 in terms of maps.
Solution would be to change client's code from `key/value` to using `first/second`.
